name: Build and deploy dotnet core project to Azure Function App - stbillingsaasfunc

on:
  push:
    branches:
      - master
    paths:
      - 'src/Functions/**'
      - 'src/Shared/**'
      - 'src/Infrastructure/**'
      - '.github/workflows/deploy_functions.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/Functions'
  DOTNET_VERSION: '10.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Publicar Proyecto de Azure Functions'
        run: |
          dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/Functions.csproj --configuration Release --output ./output-func

      - name: 'Desplegar en Azure Functions'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'stbillingsaasfunc'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: './output-func'